### ISSUE TITLE
1.0 Beta Release Checklist

### ISSUE THREAD

**Issue by linucksrox** [linucksrox/ReminderList#1]
- [x] Don't schedule the reminder until the item is checked off the list
- [x] Uncheck item at time of notification
- [x] Refine notification message (should reiterate the item details, and link to the app when clicked on)
- [x] Cancel schedule for item if user manually unchecks the item
- [x] Allow user to define the schedule per item
- [x] In Worker, if item is already unchecked do nothing (not even notify) as this indicates the user manually unchecked the item and for some reason the worker was not cancelled (not sure if this can happen or not).
- [x] Clear #2 
- [x] Clear #8 
- [x] Clear #3 
- [x] Clear #5 
- [x] Clear #13 
- [x] Clear #4 
- [x] Clear #16 
- [x] Get an app icon
